# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-30 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('life', '0003_auto_20180429_1022'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lpost',
            options={'verbose_name': '\u6162\u751f\u6d3b', 'verbose_name_plural': '\u6162\u751f\u6d3b'},
        ),
    ]
