# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-27 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='spicture',
            name='post',
        ),
        migrations.AddField(
            model_name='spost',
            name='img',
            field=models.ImageField(default='abc', upload_to='SImg'),
        ),
        migrations.DeleteModel(
            name='SPicture',
        ),
    ]
