# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-27 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0002_auto_20180427_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spost',
            name='img',
            field=models.ImageField(upload_to='SImg'),
        ),
    ]
