# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-29 01:42
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0003_auto_20180427_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scategory',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='spost',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u4f5c\u8005'),
        ),
        migrations.AlterField(
            model_name='spost',
            name='body',
            field=models.TextField(verbose_name='\u5185\u5bb9'),
        ),
        migrations.AlterField(
            model_name='spost',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Study.SCategory', verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='spost',
            name='created_time',
            field=models.DateTimeField(verbose_name='\u521b\u5efa\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='spost',
            name='excerpt',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='spost',
            name='img',
            field=models.ImageField(upload_to='SImg', verbose_name='\u914d\u56fe'),
        ),
        migrations.AlterField(
            model_name='spost',
            name='modified_time',
            field=models.DateTimeField(verbose_name='\u4fee\u6539\u65e5\u671f'),
        ),
        migrations.AlterField(
            model_name='spost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='Study.STag', verbose_name='\u6807\u7b7e'),
        ),
        migrations.AlterField(
            model_name='spost',
            name='title',
            field=models.CharField(max_length=70, verbose_name='\u6807\u9898'),
        ),
        migrations.AlterField(
            model_name='stag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u6807\u7b7e'),
        ),
    ]
