# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-30 07:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Study', '0004_auto_20180429_0942'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scategory',
            options={'verbose_name': '\u5206\u7c7b', 'verbose_name_plural': '\u5206\u7c7b'},
        ),
        migrations.AlterModelOptions(
            name='spost',
            options={'verbose_name': '\u5b66\u65e0\u6b62\u5883', 'verbose_name_plural': '\u5b66\u65e0\u6b62\u5883'},
        ),
        migrations.AlterModelOptions(
            name='stag',
            options={'verbose_name': '\u6807\u7b7e', 'verbose_name_plural': '\u6807\u7b7e'},
        ),
    ]
